### ISSUE TITLE
TypeError when running key-compromise option

### ISSUE THREAD

**Issue by toniblyx** [ThreatResponse/aws_ir#24]
Error found when running key-compromise 
$ aws_ir key-compromise --access-key-id AKIASAMPLE
2017-02-22 04:22:27,834 - aws_ir.cli - INFO - Parsing successful proceeding to incident plan.
2017-02-22 04:22:32,717 - aws_ir.cli - INFO - Attempting key disable.
Traceback (most recent call last):
  File "/usr/local/bin/aws_ir", line 10, in <module>
    c.run()
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/cli.py", line 168, in run
    kc.mitigate()
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/plans/key.py", line 66, in mitigate
    dry_run=False
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/plugins/revokests_key.py", line 21, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/plugins/revokests_key.py", line 27, in setup
    policy_document = self.__generate_inline_policy()
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/plugins/revokests_key.py", line 66, in __generate_inline_policy
    template_file = open(template_name)
TypeError: coercing to Unicode: need string or buffer, NoneType found

aws_ir (0.2.1) installed with pip in EC2 / Ubuntu 14.04.5 LTS

**Comment by andrewkrug** [comment]
@joelferrier do you think this unicode issue is similar to what we ran into with margarita shotgun or maybe it can't find the template?

**Comment by toniblyx** [comment]
Just to add more context here, running aws_ir from the cloned repo it works fine (./bin/aws_ir), the issue seems to be only using the pip version.

**Comment by joelferrier** [comment]
The problem seems to be that the `templates/deny-sts-before-time.json.j2` file is being referenced relative to the current working directory, instead of finding the module base path and appending the template path.

`import aws_ir`
`print(aws_ir.__file__)`

**Comment by joelferrier** [comment]
This is fixed on the development branch with 4750c24
