### ISSUE TITLE
IAM policy/requirements to use aws_ir ? UnboundLocalError: local variable 'security_group_result' referenced before assignment

### ISSUE THREAD

**Issue by juju4** [ThreatResponse/aws_ir#32]
Hello,
Finally taking a bit of time to test aws_ir and having basic issues. Not using aws enough day-to-day.
Sorry if it's really basic

I setup a dedicated t2.micro as webserver to test IR and create a dedicated aws_ir user.
On user IAM, docs (https://aws-ir.readthedocs.io/en/latest/quickstart.html) say "Check back soon for an IAM policy featuring the minimum set of required permissions"
I tried with following blog post http://threatresponse.cloud/blog/2016/tips_for_least_privilege_iam_policies.html

But after install 
```
# apt-get install libssl-dev python-dev python-pip libyaml-dev
# pip install awscli aws_ir
$ aws configure
[...]
$ aws ec2 describe-instances
[OK. Ensure Clock is fine (with or without *ntpd) and firewall too (curl -v https://ec2.us-east-1.amazonaws.com/ = HTTP 301). can be from systems inside and outside amazon]
```

```
# aws_ir instance-compromise --instance-ip 54.165.132.241 --user aws_ir --ssh-key awsweb.pem 
2017-04-01T19:38:42 - aws_ir.cli - INFO - Initialization successful proceeding to incident plan.
2017-04-01T19:38:42 - aws_ir.libs.case - INFO - Initial connection to AmazonWebServices made.
2017-04-01T19:38:52 - aws_ir.libs.case - INFO - Inventory AWS Regions Complete 14 found.
2017-04-01T19:38:52 - aws_ir.libs.case - INFO - Inventory Availability Zones Complete 35 found.
2017-04-01T19:38:52 - aws_ir.libs.case - INFO - Beginning inventory of resources world wide.  This might take a minute...
2017-04-01T19:39:04 - aws_ir.libs.case - INFO - Inventory complete.  Proceeding to resource identification.
Traceback (most recent call last):
  File "/usr/local/bin/aws_ir", line 10, in <module>
    c.run()
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/cli.py", line 154, in run
    hc.mitigate()
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/plans/host.py", line 79, in mitigate
    dry_run=False
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/plugins/isolate_host.py", line 18, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/plugins/isolate_host.py", line 21, in setup
    sg = self.__create_isolation_security_group()
  File "/usr/local/lib/python2.7/dist-packages/aws_ir/plugins/isolate_host.py", line 57, in __create_isolation_security_group
    return security_group_result['GroupId']
UnboundLocalError: local variable 'security_group_result' referenced before assignment
```

Current IAM policy a bit extended from above blog post
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cloudtrail:DescribeTrails",
                "cloudwatch:DescribeAlarms",
                "ec2:DescribeFlowLogs",
                "ec2:DescribeRegions",
                "ec2:DescribeVpcs",
                "ec2:DescribeInstances",
                "ec2:DescribeAvailabilityZones",
                "iam:GenerateCredentialReport",
                "iam:GetCredentialReport",
                "iam:ListAttachedUserPolicies",
                "iam:ListRoles",
                "s3:GetBucketAcl",
                "s3:GetBucketLogging",
                "s3:GetBucketVersioning",
                "s3:ListAllMyBuckets",
                "s3:CreateBucket",
                "s3:PutBucketAcl",
                "s3:PutBucketTagging",
                "s3:PutBucketVersioning",
                "s3:ListBucket"
            ],
            "Resource": "*"
        }
    ]
}
```

Thanks

**Comment by andrewkrug** [comment]
@juju4 there is a better boiler plate policy.  I don't think this quite had all the permissions you need.  I'll see about getting that posted and you can test again.  Thanks for your issue!

**Comment by vegardvaage** [comment]
Any updates on this? I'd be interested to try aws_ir as well, but it seems the docs aren't complete yet.

**Comment by andrewkrug** [comment]
@juju4 @vegardvaage This is pretty close I think.  Can I get one of you to test this?

```
{
	"AWSTemplateFormatVersion" : "2010-09-09",
	"Description" : "Incident Pony security write cross-account role template.",
	"Parameters" : {
	},
  "Resources" : {
    "AWS_IRWriteRole" : {
      "Type": "AWS::IAM::Role",
      "Properties" : {
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/SecurityAudit"
        ]
      }
    },
  "AWS_IRWritePolicy": {
    "Type": "AWS::IAM::ManagedPolicy",
    "Properties": {
      "Description" : "Ability for inicident pony to perform specific response operations in the customer account.",
      "PolicyDocument" : {
        "Version" : "2012-10-17",
        "Statement": [{
            "Action": [
              "ec2:AttachVolume",
              "ec2:AuthorizeSecurityGroupEgress",
              "ec2:AuthorizeSecurityGroupIngress",
              "ec2:CopyImage",
              "ec2:CopySnapshot",
              "ec2:CreateFlowLogs",
              "ec2:CreateImage",
              "ec2:CreateKeyPair",
              "ec2:CreateNetworkAcl",
              "ec2:CreateNetworkAclEntry",
              "ec2:CreateSecurityGroup",
              "ec2:CreateSnapshot",
              "ec2:CreateSubnet",
              "ec2:CreateTags",
              "ec2:DetachNetworkInterface",
              "ec2:DetachVolume",
              "ec2:GetConsoleOutput",
              "ec2:GetConsoleScreenshot",
              "ec2:ImportImage",
              "ec2:ImportInstance",
              "ec2:ImportKeyPair",
              "ec2:ImportSnapshot",
              "ec2:ImportVolume",
              "ec2:ModifyInstanceAttribute",
              "ec2:ModifySnapshotAttribute",
              "ec2:ModifySubnetAttribute",
              "ec2:ModifyVolumeAttribute",
              "ec2:RebootInstances",
              "ec2:ReportInstanceStatus",
              "ec2:ResetSnapshotAttribute",
              "ec2:RestoreAddressToClassic",
              "ec2:RevokeSecurityGroupEgress",
              "ec2:RevokeSecurityGroupIngress",
              "ec2:StopInstances",
              "iam:AddRoleToInstanceProfile",
              "iam:AttachRolePolicy",
              "iam:AttachUserPolicy",
              "iam:DetachRolePolicy",
              "iam:DetachUserPolicy",
              "iam:CreatePolicy",
              "iam:PutRolePolicy",
              "iam:PutUserPolicy",
              "iam:UpdateAccessKey",
              "iam:UpdateUser",
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:DescribeDestinations",
              "logs:DescribeExportTasks",
              "logs:DescribeLogGroups",
              "logs:DescribeLogStreams",
              "logs:DescribeMetricFilters",
              "logs:DescribeSubscriptionFilters",
              "logs:FilterLogEvents",
              "logs:GetLogEvents",
              "logs:PutDestination",
              "logs:PutDestinationPolicy",
              "logs:PutLogEvents",
              "logs:PutMetricFilter",
              "logs:PutRetentionPolicy",
              "logs:PutSubscriptionFilter",
              "logs:TestMetricFilter"
              ],
              "Effect": "Allow",
              "Resource": "*"
          }]
        },
        "Roles" : [ { "Ref" : "AWS_IRWriteRole" }  ]
      }
    }
  },
  "Outputs" : {
    "AWS_IRWriteRoleArn" : {
      "Description" 	: "The role ARN of the cross-account user. Copy this into Incident Pony.",
      "Value"			: { "Fn::GetAtt" : ["AWS_IRWriteRole", "Arn"] }
    }
  }
}
```

**Comment by vegardvaage** [comment]
I'll give it a shot this week, thanks!

**Comment by vegardvaage** [comment]
Using the following policy (based on the above template) I got this error:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws_ir", line 10, in <module>
    c.run()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/cli.py", line 129, in run
    self.config.bucket_name
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/libs/case.py", line 35, in __init__
    self.case_bucket = self.__setup_bucket(region='us-west-2')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/libs/case.py", line 146, in __setup_bucket
    region
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/libs/s3bucket.py", line 17, in __init__
    self.bucket = self.find_or_create_by()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/libs/s3bucket.py", line 20, in find_or_create_by
    bucket = self.__locate_bucket()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/libs/s3bucket.py", line 89, in __locate_bucket
    for bucket in buckets:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto3/resources/collection.py", line 161, in pages
    pages = [getattr(client, self._py_operation_name)(**params)]
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied
```

There doesn't seem to be any S3 permissions? 

```
{
    "Version": "2012-10-17",
    "Statement": {
        "Action": [
            "ec2:AttachVolume",
            "ec2:AuthorizeSecurityGroupEgress",
            "ec2:AuthorizeSecurityGroupIngress",
            "ec2:CopyImage",
            "ec2:CopySnapshot",
            "ec2:CreateFlowLogs",
            "ec2:CreateImage",
            "ec2:CreateKeyPair",
            "ec2:CreateNetworkAcl",
            "ec2:CreateNetworkAclEntry",
            "ec2:CreateSecurityGroup",
            "ec2:CreateSnapshot",
            "ec2:CreateSubnet",
            "ec2:CreateTags",
            "ec2:DetachNetworkInterface",
            "ec2:DetachVolume",
            "ec2:GetConsoleOutput",
            "ec2:GetConsoleScreenshot",
            "ec2:ImportImage",
            "ec2:ImportInstance",
            "ec2:ImportKeyPair",
            "ec2:ImportSnapshot",
            "ec2:ImportVolume",
            "ec2:ModifyInstanceAttribute",
            "ec2:ModifySnapshotAttribute",
            "ec2:ModifySubnetAttribute",
            "ec2:ModifyVolumeAttribute",
            "ec2:RebootInstances",
            "ec2:ReportInstanceStatus",
            "ec2:ResetSnapshotAttribute",
            "ec2:RestoreAddressToClassic",
            "ec2:RevokeSecurityGroupEgress",
            "ec2:RevokeSecurityGroupIngress",
            "ec2:StopInstances",
            "iam:AddRoleToInstanceProfile",
            "iam:AttachRolePolicy",
            "iam:AttachUserPolicy",
            "iam:DetachRolePolicy",
            "iam:DetachUserPolicy",
            "iam:CreatePolicy",
            "iam:PutRolePolicy",
            "iam:PutUserPolicy",
            "iam:UpdateAccessKey",
            "iam:UpdateUser",
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:DescribeDestinations",
            "logs:DescribeExportTasks",
            "logs:DescribeLogGroups",
            "logs:DescribeLogStreams",
            "logs:DescribeMetricFilters",
            "logs:DescribeSubscriptionFilters",
            "logs:FilterLogEvents",
            "logs:GetLogEvents",
            "logs:PutDestination",
            "logs:PutDestinationPolicy",
            "logs:PutLogEvents",
            "logs:PutMetricFilter",
            "logs:PutRetentionPolicy",
            "logs:PutSubscriptionFilter",
            "logs:TestMetricFilter"
        ],
        "Effect": "Allow",
        "Resource": "*"
    }
}
```

**Comment by andrewkrug** [comment]
Good catch.  There's a few different ways you could handle s3 permissions for file deposit here.  At a minimum we need to be able to create a bucket, list bucket, and put to buckets that start with cloud-response-* .  I can add that to this policy or if you wanted to add those s3 permissions and post them here that would be great.

**Comment by vegardvaage** [comment]
The following seems to work as far as permissions go, but I'm getting an error related to a missing region now:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:AttachVolume",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CopyImage",
                "ec2:CopySnapshot",
                "ec2:CreateFlowLogs",
                "ec2:CreateImage",
                "ec2:CreateKeyPair",
                "ec2:CreateNetworkAcl",
                "ec2:CreateNetworkAclEntry",
                "ec2:CreateSecurityGroup",
                "ec2:CreateSnapshot",
                "ec2:CreateSubnet",
                "ec2:CreateTags",
                "ec2:DetachNetworkInterface",
                "ec2:DetachVolume",
                "ec2:GetConsoleOutput",
                "ec2:GetConsoleScreenshot",
                "ec2:ImportImage",
                "ec2:ImportInstance",
                "ec2:ImportKeyPair",
                "ec2:ImportSnapshot",
                "ec2:ImportVolume",
                "ec2:ModifyInstanceAttribute",
                "ec2:ModifySnapshotAttribute",
                "ec2:ModifySubnetAttribute",
                "ec2:ModifyVolumeAttribute",
                "ec2:RebootInstances",
                "ec2:ReportInstanceStatus",
                "ec2:ResetSnapshotAttribute",
                "ec2:RestoreAddressToClassic",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:StopInstances",
                "iam:AddRoleToInstanceProfile",
                "iam:AttachRolePolicy",
                "iam:AttachUserPolicy",
                "iam:DetachRolePolicy",
                "iam:DetachUserPolicy",
                "iam:CreatePolicy",
                "iam:PutRolePolicy",
                "iam:PutUserPolicy",
                "iam:UpdateAccessKey",
                "iam:UpdateUser",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:DescribeDestinations",
                "logs:DescribeExportTasks",
                "logs:DescribeLogGroups",
                "logs:DescribeLogStreams",
                "logs:DescribeMetricFilters",
                "logs:DescribeSubscriptionFilters",
                "logs:FilterLogEvents",
                "logs:GetLogEvents",
                "logs:PutDestination",
                "logs:PutDestinationPolicy",
                "logs:PutLogEvents",
                "logs:PutMetricFilter",
                "logs:PutRetentionPolicy",
                "logs:PutSubscriptionFilter",
                "logs:TestMetricFilter"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:ListBucket",
                "s3:CreateBucket",
                "s3:PutBucketAcl",
                "s3:PutBucketTagging",
                "s3:PutBucketVersioning"
            ],
            "Resource": "arn:aws:s3:::cloud-response-*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::*"
        }
    ]
}
```

```
aws_ir instance-compromise --instance-ip 1.2.3.4 --user ubuntu --ssh-key .ssh/infosec-keys.pem
2017-05-30T06:34:32 - aws_ir.cli - INFO - Initialization successful proceeding to incident plan.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/aws_ir", line 10, in <module>
    c.run()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/cli.py", line 154, in run
    hc.mitigate()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/plans/host.py", line 54, in mitigate
    self.case.prep_aws_connections()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/libs/case.py", line 44, in prep_aws_connections
    service='ec2'
  File "/home/ubuntu/.local/lib/python2.7/site-packages/aws_ir/libs/connection.py", line 18, in connect
    region_name=self.region
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/args.py", line 103, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 297, in resolve
    service_name, region_name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by andrewkrug** [comment]
@vegardvaage this should currently be fixed in the development branch.

**Comment by andrewkrug** [comment]
@juju4 I believe I've taken care of this error in the development branch commit https://github.com/ThreatResponse/aws_ir/commit/3920e1e68cc4daf444d8afe25c506e1ca75ae739

**Comment by andrewkrug** [comment]
@juju4 @vegardvaage I'm going to close this issue on the network isolation but feel free to start a new one for the privileges if that's still an issue and you'd like a cloudformation template.
