### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by lovecashmeer** [ThreatResponse/aws_ir#72]
aws_ir key-compromise --access-key-id AKIA****928****8

I get the following error while executing this command

2018-01-19T22:47:56 - aws_ir.cli - INFO - Initialization successful proceeding to incident plan.
2018-01-19T22:47:56 - aws_ir.plans.key - INFO - Attempting key disable.
Traceback (most recent call last):
  File "/usr/local/bin/aws_ir", line 10, in <module>
    c.run()
  File "/usr/local/lib/python2.7/site-packages/aws_ir/cli.py", line 245, in run
    kc.mitigate()
  File "/usr/local/lib/python2.7/site-packages/aws_ir/plans/key.py", line 62, in mitigate
    dry_run=False
  File "/usr/local/lib/python2.7/site-packages/aws_ir_plugins/revokests_key.py", line 25, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/site-packages/aws_ir_plugins/revokests_key.py", line 29, in setup
    self.template = self._generate_inline_policy()
  File "/usr/local/lib/python2.7/site-packages/aws_ir_plugins/revokests_key.py", line 77, in _generate_inline_policy
    template_file = open(template_name)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by jparr** [comment]
Try using python 3 aws_ir is developed using python 3 and we are not supporting 2.7 anymore.
