### ISSUE TITLE
KeyError: 'VpcId' - Instances assigned to VPCs not supported? 

### ISSUE THREAD

**Issue by g2892118** [ThreatResponse/aws_ir#82]
I'm receiving the following error when trying to launch aws_ir 0.3.1 built from git, with the compromise type of instance-compromise. There is a VPC ID assigned to the particular instance being passed to aws_ir. Are instances assigned to VPCs not supported?

![image](https://user-images.githubusercontent.com/38674753/39159896-1c9d34a0-471d-11e8-8c32-2ac635381366.png)

**Comment by jparr** [comment]
It looks like you didn't provide a proper instance id. --target needs to be an instance id or ip address. Sorry the error message was not helpful.

**Comment by andrewkrug** [comment]
Closing this issue out as it has not been updated in some time.

**Comment by senormg** [comment]
I recently have setup aws_ir (0.3.3) and I am receiving a similar 'KeyError' stack trace when attempting to use the instance-compromise subcommand. The key-compromise command is working fantastically.

Are there any other arguments/commands I should be providing? I have attempted both the instance-id and ip-address with no luck.

`aws_ir --examiner-cidr-range '4.4.4.4/32' instance-compromise --target 52.40.162.126 --user bob --ssh-key ~/.ssh/key_file
2019-06-04T14:22:48 - aws_ir.cli - INFO - Initialization successful proceeding to incident plan.
2019-06-04T14:22:48 - aws_ir.libs.case - INFO - Initial connection to AmazonWebServices made.
2019-06-04T14:22:57 - aws_ir.libs.case - INFO - Inventory AWS Regions Complete 16 found.
2019-06-04T14:22:57 - aws_ir.libs.case - INFO - Inventory Availability Zones Complete 51 found.
2019-06-04T14:22:57 - aws_ir.libs.case - INFO - Beginning inventory of resources world wide.  This might take a minute...
2019-06-04T14:22:57 - aws_ir.libs.inventory - INFO - Searching eu-north-1 for instance.
2019-06-04T14:22:57 - aws_ir.libs.inventory - INFO - Searching ap-south-1 for instance.
2019-06-04T14:22:58 - aws_ir.libs.inventory - INFO - Searching eu-west-3 for instance.
2019-06-04T14:22:58 - aws_ir.libs.inventory - INFO - Searching eu-west-2 for instance.
2019-06-04T14:22:59 - aws_ir.libs.inventory - INFO - Searching eu-west-1 for instance.
2019-06-04T14:22:59 - aws_ir.libs.inventory - INFO - Searching ap-northeast-2 for instance.
2019-06-04T14:23:00 - aws_ir.libs.inventory - INFO - Searching ap-northeast-1 for instance.
2019-06-04T14:23:01 - aws_ir.libs.inventory - INFO - Searching sa-east-1 for instance.
2019-06-04T14:23:01 - aws_ir.libs.inventory - INFO - Searching ca-central-1 for instance.
2019-06-04T14:23:02 - aws_ir.libs.inventory - INFO - Searching ap-southeast-1 for instance.
2019-06-04T14:23:02 - aws_ir.libs.inventory - INFO - Searching ap-southeast-2 for instance.
2019-06-04T14:23:03 - aws_ir.libs.inventory - INFO - Searching eu-central-1 for instance.
2019-06-04T14:23:04 - aws_ir.libs.inventory - INFO - Searching us-east-1 for instance.
Traceback (most recent call last):
  File "/root/awsir/bin/aws_ir", line 10, in <module>
    c.run()
  File "/root/awsir/lib/python3.5/site-packages/aws_ir/cli.py", line 197, in run
    case_obj.prep_aws_connections()
  File "/root/awsir/lib/python3.5/site-packages/aws_ir/libs/case.py", line 84, in prep_aws_connections
    self.available_regions
  File "/root/awsir/lib/python3.5/site-packages/aws_ir/libs/inventory.py", line 72, in __init__
    self.type
  File "/root/awsir/lib/python3.5/site-packages/aws_ir/libs/inventory.py", line 11, in __init__
    self.result = self.get_all_running_from_aws()
  File "/root/awsir/lib/python3.5/site-packages/aws_ir/libs/inventory.py", line 51, in get_all_running_from_aws
    inventory[region] = self.get_running_by_region_aws(region)
  File "/root/awsir/lib/python3.5/site-packages/aws_ir/libs/inventory.py", line 24, in get_running_by_region_aws
    instance_data = self._extract_data_aws(instance, region)
  File "/root/awsir/lib/python3.5/site-packages/aws_ir/libs/inventory.py", line 36, in _extract_data_aws
    vpc_id=instance['VpcId'],
KeyError: 'VpcId'`

Thank you for your time and insight.
